server:
  port: 8080

spring:
  profiles:
    active: ${EVN_DEV}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/local?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: 123456
  application:
    name: eip-gateway
  jpa:
    show-sql: true

mybatis:
  mapper-locations: /sqlmap/*.xml
  type-aliases-package: com.cxist.eip.gateway.entity
